import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Clean-architecture boundaries, enforced by the build rather than by review.
 *
 * Dependencies point inward: domain knows nothing, application knows domain,
 * infrastructure implements the ports, and the delivery layer (app/, components/)
 * talks to application and domain — never to a concrete adapter.
 *
 * This existed only as a convention before, and it had already eroded in three
 * separate ways that this migration had to undo:
 *
 *   - 11 components imported their prop types from Supabase service modules,
 *     so a database row shape was a React prop.
 *   - `infrastructure/rate-card.ts` imported its return types FROM a React
 *     component, pointing the dependency arrow backwards through every layer.
 *   - 67 files under app/ reached straight past the application layer into
 *     infrastructure.
 *
 * A rule catches the next one on the day it is written, which is the only time
 * it is cheap to fix.
 */
const LAYER_RULES = [
  {
    // Innermost ring: pure. No framework, no I/O, no knowledge of anything.
    files: ["src/domain/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", {
        patterns: [
          {
            group: [
              "@/infrastructure/*", "@/app/*", "@/components/*", "@/lib/*",
              "next", "next/*", "react", "react-dom", "drizzle-orm", "drizzle-orm/*",
              "better-auth", "better-auth/*", "pg", "@aws-sdk/*",
            ],
            message:
              "domain/ must stay pure — no framework, no I/O, no outer layers. " +
              "If a domain type needs data, express it as a port the outside implements.",
          },
        ],
      }],
    },
  },
  {
    // Application: orchestrates domain through ports. Knows no concrete adapter.
    files: ["src/application/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", {
        patterns: [
          {
            group: [
              "@/infrastructure/*", "@/app/*", "@/components/*",
              "next", "next/*", "drizzle-orm", "drizzle-orm/*",
              "better-auth", "better-auth/*", "pg",
            ],
            message:
              "application/ may import @/domain only. Take dependencies as " +
              "injected ports (see CatalogDeps / CheckoutDeps).",
          },
        ],
      }],
    },
  },
  {
    // Infrastructure implements ports; it must never depend on the UI.
    files: ["src/infrastructure/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", {
        patterns: [
          {
            group: ["@/components/*", "@/app/*"],
            message:
              "infrastructure/ must not import from the delivery layer. If a " +
              "type is shared, it belongs in @/domain/entities.",
          },
        ],
      }],
    },
  },
  {
    // Delivery layer: pages, actions and components.
    files: ["src/app/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": ["error", {
        patterns: [
          {
            group: [
              "@/infrastructure/db/schema",
              "@/infrastructure/db/schema/*",
              "@/infrastructure/db/client",
              "drizzle-orm/pg-core",
            ],
            message:
              "Do not reach into the database schema from a page or component. " +
              "Call a service or repository, and take types from @/domain/entities.",
          },
        ],
      }],
    },
  },
  {
    /**
     * Server Actions and Route Handlers are the composition root: they are
     * where a concrete adapter is legitimately named. They still may not touch
     * the raw schema, which the rule above already covers.
     */
    files: [
      "src/app/**/actions.ts",
      "src/app/**/*-actions.ts",
      "src/app/**/route.ts",
    ],
    rules: { "no-restricted-imports": "off" },
  },
  {
    /**
     * Generated by drizzle-kit. Our rules do not apply, and the unused-parameter
     * warnings are drizzle's own output shape — it emits `(table) => [...]` even
     * where the callback ignores its argument. Linting a file nobody edits by
     * hand only trains people to ignore warnings.
     */
    files: ["src/infrastructure/db/schema/tables.ts", "src/infrastructure/db/schema/relations.ts"],
    rules: {
      "no-restricted-imports": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  ...LAYER_RULES,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated schema + one-shot migration scripts.
    "db/**",
    "scripts/**",
  ]),
]);

export default eslintConfig;
