/**
 * Canonical ISO 3166-1 country/territory dataset for worldwide shipping.
 *
 * This is the single source of truth for the *set* of shippable places. The
 * database (`shipping_countries`) is seeded from it, so runtime code can read
 * flags/zones/names without a DB round-trip, and admins toggle availability and
 * rates per country in the DB.
 *
 * Flags are derived from the alpha-2 code (Unicode regional-indicator letters),
 * so there are no image assets to load.
 */

export type ShippingZone =
  | "Africa"
  | "Europe"
  | "Asia"
  | "North America"
  | "South America"
  | "Oceania"
  | "Antarctica";

export const SHIPPING_ZONES: ShippingZone[] = [
  "Africa",
  "Europe",
  "Asia",
  "North America",
  "South America",
  "Oceania",
  "Antarctica",
];

export interface Country {
  /** ISO 3166-1 alpha-2 code (uppercase). */
  readonly code: string;
  readonly name: string;
  readonly zone: ShippingZone;
}

/** Turn an alpha-2 code into its flag emoji (e.g. "NG" → 🇳🇬). */
export function flagEmoji(code: string): string {
  const cc = code.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(cc)) return "🏳️";
  return String.fromCodePoint(
    ...[...cc].map((c) => 0x1f1e6 - 65 + c.charCodeAt(0)),
  );
}

// prettier-ignore
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", zone: "Asia" },
  { code: "AX", name: "Åland Islands", zone: "Europe" },
  { code: "AL", name: "Albania", zone: "Europe" },
  { code: "DZ", name: "Algeria", zone: "Africa" },
  { code: "AS", name: "American Samoa", zone: "Oceania" },
  { code: "AD", name: "Andorra", zone: "Europe" },
  { code: "AO", name: "Angola", zone: "Africa" },
  { code: "AI", name: "Anguilla", zone: "North America" },
  { code: "AQ", name: "Antarctica", zone: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda", zone: "North America" },
  { code: "AR", name: "Argentina", zone: "South America" },
  { code: "AM", name: "Armenia", zone: "Asia" },
  { code: "AW", name: "Aruba", zone: "North America" },
  { code: "AU", name: "Australia", zone: "Oceania" },
  { code: "AT", name: "Austria", zone: "Europe" },
  { code: "AZ", name: "Azerbaijan", zone: "Asia" },
  { code: "BS", name: "Bahamas", zone: "North America" },
  { code: "BH", name: "Bahrain", zone: "Asia" },
  { code: "BD", name: "Bangladesh", zone: "Asia" },
  { code: "BB", name: "Barbados", zone: "North America" },
  { code: "BY", name: "Belarus", zone: "Europe" },
  { code: "BE", name: "Belgium", zone: "Europe" },
  { code: "BZ", name: "Belize", zone: "North America" },
  { code: "BJ", name: "Benin", zone: "Africa" },
  { code: "BM", name: "Bermuda", zone: "North America" },
  { code: "BT", name: "Bhutan", zone: "Asia" },
  { code: "BO", name: "Bolivia", zone: "South America" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", zone: "North America" },
  { code: "BA", name: "Bosnia and Herzegovina", zone: "Europe" },
  { code: "BW", name: "Botswana", zone: "Africa" },
  { code: "BV", name: "Bouvet Island", zone: "Antarctica" },
  { code: "BR", name: "Brazil", zone: "South America" },
  { code: "IO", name: "British Indian Ocean Territory", zone: "Asia" },
  { code: "BN", name: "Brunei Darussalam", zone: "Asia" },
  { code: "BG", name: "Bulgaria", zone: "Europe" },
  { code: "BF", name: "Burkina Faso", zone: "Africa" },
  { code: "BI", name: "Burundi", zone: "Africa" },
  { code: "CV", name: "Cabo Verde", zone: "Africa" },
  { code: "KH", name: "Cambodia", zone: "Asia" },
  { code: "CM", name: "Cameroon", zone: "Africa" },
  { code: "CA", name: "Canada", zone: "North America" },
  { code: "KY", name: "Cayman Islands", zone: "North America" },
  { code: "CF", name: "Central African Republic", zone: "Africa" },
  { code: "TD", name: "Chad", zone: "Africa" },
  { code: "CL", name: "Chile", zone: "South America" },
  { code: "CN", name: "China", zone: "Asia" },
  { code: "CX", name: "Christmas Island", zone: "Oceania" },
  { code: "CC", name: "Cocos (Keeling) Islands", zone: "Oceania" },
  { code: "CO", name: "Colombia", zone: "South America" },
  { code: "KM", name: "Comoros", zone: "Africa" },
  { code: "CG", name: "Congo", zone: "Africa" },
  { code: "CD", name: "Congo (Democratic Republic)", zone: "Africa" },
  { code: "CK", name: "Cook Islands", zone: "Oceania" },
  { code: "CR", name: "Costa Rica", zone: "North America" },
  { code: "CI", name: "Côte d'Ivoire", zone: "Africa" },
  { code: "HR", name: "Croatia", zone: "Europe" },
  { code: "CU", name: "Cuba", zone: "North America" },
  { code: "CW", name: "Curaçao", zone: "North America" },
  { code: "CY", name: "Cyprus", zone: "Europe" },
  { code: "CZ", name: "Czechia", zone: "Europe" },
  { code: "DK", name: "Denmark", zone: "Europe" },
  { code: "DJ", name: "Djibouti", zone: "Africa" },
  { code: "DM", name: "Dominica", zone: "North America" },
  { code: "DO", name: "Dominican Republic", zone: "North America" },
  { code: "EC", name: "Ecuador", zone: "South America" },
  { code: "EG", name: "Egypt", zone: "Africa" },
  { code: "SV", name: "El Salvador", zone: "North America" },
  { code: "GQ", name: "Equatorial Guinea", zone: "Africa" },
  { code: "ER", name: "Eritrea", zone: "Africa" },
  { code: "EE", name: "Estonia", zone: "Europe" },
  { code: "SZ", name: "Eswatini", zone: "Africa" },
  { code: "ET", name: "Ethiopia", zone: "Africa" },
  { code: "FK", name: "Falkland Islands", zone: "South America" },
  { code: "FO", name: "Faroe Islands", zone: "Europe" },
  { code: "FJ", name: "Fiji", zone: "Oceania" },
  { code: "FI", name: "Finland", zone: "Europe" },
  { code: "FR", name: "France", zone: "Europe" },
  { code: "GF", name: "French Guiana", zone: "South America" },
  { code: "PF", name: "French Polynesia", zone: "Oceania" },
  { code: "TF", name: "French Southern Territories", zone: "Antarctica" },
  { code: "GA", name: "Gabon", zone: "Africa" },
  { code: "GM", name: "Gambia", zone: "Africa" },
  { code: "GE", name: "Georgia", zone: "Asia" },
  { code: "DE", name: "Germany", zone: "Europe" },
  { code: "GH", name: "Ghana", zone: "Africa" },
  { code: "GI", name: "Gibraltar", zone: "Europe" },
  { code: "GR", name: "Greece", zone: "Europe" },
  { code: "GL", name: "Greenland", zone: "North America" },
  { code: "GD", name: "Grenada", zone: "North America" },
  { code: "GP", name: "Guadeloupe", zone: "North America" },
  { code: "GU", name: "Guam", zone: "Oceania" },
  { code: "GT", name: "Guatemala", zone: "North America" },
  { code: "GG", name: "Guernsey", zone: "Europe" },
  { code: "GN", name: "Guinea", zone: "Africa" },
  { code: "GW", name: "Guinea-Bissau", zone: "Africa" },
  { code: "GY", name: "Guyana", zone: "South America" },
  { code: "HT", name: "Haiti", zone: "North America" },
  { code: "HM", name: "Heard Island and McDonald Islands", zone: "Antarctica" },
  { code: "VA", name: "Holy See", zone: "Europe" },
  { code: "HN", name: "Honduras", zone: "North America" },
  { code: "HK", name: "Hong Kong", zone: "Asia" },
  { code: "HU", name: "Hungary", zone: "Europe" },
  { code: "IS", name: "Iceland", zone: "Europe" },
  { code: "IN", name: "India", zone: "Asia" },
  { code: "ID", name: "Indonesia", zone: "Asia" },
  { code: "IR", name: "Iran", zone: "Asia" },
  { code: "IQ", name: "Iraq", zone: "Asia" },
  { code: "IE", name: "Ireland", zone: "Europe" },
  { code: "IM", name: "Isle of Man", zone: "Europe" },
  { code: "IL", name: "Israel", zone: "Asia" },
  { code: "IT", name: "Italy", zone: "Europe" },
  { code: "JM", name: "Jamaica", zone: "North America" },
  { code: "JP", name: "Japan", zone: "Asia" },
  { code: "JE", name: "Jersey", zone: "Europe" },
  { code: "JO", name: "Jordan", zone: "Asia" },
  { code: "KZ", name: "Kazakhstan", zone: "Asia" },
  { code: "KE", name: "Kenya", zone: "Africa" },
  { code: "KI", name: "Kiribati", zone: "Oceania" },
  { code: "KP", name: "Korea (North)", zone: "Asia" },
  { code: "KR", name: "Korea (South)", zone: "Asia" },
  { code: "KW", name: "Kuwait", zone: "Asia" },
  { code: "KG", name: "Kyrgyzstan", zone: "Asia" },
  { code: "LA", name: "Laos", zone: "Asia" },
  { code: "LV", name: "Latvia", zone: "Europe" },
  { code: "LB", name: "Lebanon", zone: "Asia" },
  { code: "LS", name: "Lesotho", zone: "Africa" },
  { code: "LR", name: "Liberia", zone: "Africa" },
  { code: "LY", name: "Libya", zone: "Africa" },
  { code: "LI", name: "Liechtenstein", zone: "Europe" },
  { code: "LT", name: "Lithuania", zone: "Europe" },
  { code: "LU", name: "Luxembourg", zone: "Europe" },
  { code: "MO", name: "Macao", zone: "Asia" },
  { code: "MG", name: "Madagascar", zone: "Africa" },
  { code: "MW", name: "Malawi", zone: "Africa" },
  { code: "MY", name: "Malaysia", zone: "Asia" },
  { code: "MV", name: "Maldives", zone: "Asia" },
  { code: "ML", name: "Mali", zone: "Africa" },
  { code: "MT", name: "Malta", zone: "Europe" },
  { code: "MH", name: "Marshall Islands", zone: "Oceania" },
  { code: "MQ", name: "Martinique", zone: "North America" },
  { code: "MR", name: "Mauritania", zone: "Africa" },
  { code: "MU", name: "Mauritius", zone: "Africa" },
  { code: "YT", name: "Mayotte", zone: "Africa" },
  { code: "MX", name: "Mexico", zone: "North America" },
  { code: "FM", name: "Micronesia", zone: "Oceania" },
  { code: "MD", name: "Moldova", zone: "Europe" },
  { code: "MC", name: "Monaco", zone: "Europe" },
  { code: "MN", name: "Mongolia", zone: "Asia" },
  { code: "ME", name: "Montenegro", zone: "Europe" },
  { code: "MS", name: "Montserrat", zone: "North America" },
  { code: "MA", name: "Morocco", zone: "Africa" },
  { code: "MZ", name: "Mozambique", zone: "Africa" },
  { code: "MM", name: "Myanmar", zone: "Asia" },
  { code: "NA", name: "Namibia", zone: "Africa" },
  { code: "NR", name: "Nauru", zone: "Oceania" },
  { code: "NP", name: "Nepal", zone: "Asia" },
  { code: "NL", name: "Netherlands", zone: "Europe" },
  { code: "NC", name: "New Caledonia", zone: "Oceania" },
  { code: "NZ", name: "New Zealand", zone: "Oceania" },
  { code: "NI", name: "Nicaragua", zone: "North America" },
  { code: "NE", name: "Niger", zone: "Africa" },
  { code: "NG", name: "Nigeria", zone: "Africa" },
  { code: "NU", name: "Niue", zone: "Oceania" },
  { code: "NF", name: "Norfolk Island", zone: "Oceania" },
  { code: "MK", name: "North Macedonia", zone: "Europe" },
  { code: "MP", name: "Northern Mariana Islands", zone: "Oceania" },
  { code: "NO", name: "Norway", zone: "Europe" },
  { code: "OM", name: "Oman", zone: "Asia" },
  { code: "PK", name: "Pakistan", zone: "Asia" },
  { code: "PW", name: "Palau", zone: "Oceania" },
  { code: "PS", name: "Palestine", zone: "Asia" },
  { code: "PA", name: "Panama", zone: "North America" },
  { code: "PG", name: "Papua New Guinea", zone: "Oceania" },
  { code: "PY", name: "Paraguay", zone: "South America" },
  { code: "PE", name: "Peru", zone: "South America" },
  { code: "PH", name: "Philippines", zone: "Asia" },
  { code: "PN", name: "Pitcairn", zone: "Oceania" },
  { code: "PL", name: "Poland", zone: "Europe" },
  { code: "PT", name: "Portugal", zone: "Europe" },
  { code: "PR", name: "Puerto Rico", zone: "North America" },
  { code: "QA", name: "Qatar", zone: "Asia" },
  { code: "RE", name: "Réunion", zone: "Africa" },
  { code: "RO", name: "Romania", zone: "Europe" },
  { code: "RU", name: "Russia", zone: "Europe" },
  { code: "RW", name: "Rwanda", zone: "Africa" },
  { code: "BL", name: "Saint Barthélemy", zone: "North America" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", zone: "Africa" },
  { code: "KN", name: "Saint Kitts and Nevis", zone: "North America" },
  { code: "LC", name: "Saint Lucia", zone: "North America" },
  { code: "MF", name: "Saint Martin (French part)", zone: "North America" },
  { code: "PM", name: "Saint Pierre and Miquelon", zone: "North America" },
  { code: "VC", name: "Saint Vincent and the Grenadines", zone: "North America" },
  { code: "WS", name: "Samoa", zone: "Oceania" },
  { code: "SM", name: "San Marino", zone: "Europe" },
  { code: "ST", name: "Sao Tome and Principe", zone: "Africa" },
  { code: "SA", name: "Saudi Arabia", zone: "Asia" },
  { code: "SN", name: "Senegal", zone: "Africa" },
  { code: "RS", name: "Serbia", zone: "Europe" },
  { code: "SC", name: "Seychelles", zone: "Africa" },
  { code: "SL", name: "Sierra Leone", zone: "Africa" },
  { code: "SG", name: "Singapore", zone: "Asia" },
  { code: "SX", name: "Sint Maarten (Dutch part)", zone: "North America" },
  { code: "SK", name: "Slovakia", zone: "Europe" },
  { code: "SI", name: "Slovenia", zone: "Europe" },
  { code: "SB", name: "Solomon Islands", zone: "Oceania" },
  { code: "SO", name: "Somalia", zone: "Africa" },
  { code: "ZA", name: "South Africa", zone: "Africa" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", zone: "Antarctica" },
  { code: "SS", name: "South Sudan", zone: "Africa" },
  { code: "ES", name: "Spain", zone: "Europe" },
  { code: "LK", name: "Sri Lanka", zone: "Asia" },
  { code: "SD", name: "Sudan", zone: "Africa" },
  { code: "SR", name: "Suriname", zone: "South America" },
  { code: "SJ", name: "Svalbard and Jan Mayen", zone: "Europe" },
  { code: "SE", name: "Sweden", zone: "Europe" },
  { code: "CH", name: "Switzerland", zone: "Europe" },
  { code: "SY", name: "Syria", zone: "Asia" },
  { code: "TW", name: "Taiwan", zone: "Asia" },
  { code: "TJ", name: "Tajikistan", zone: "Asia" },
  { code: "TZ", name: "Tanzania", zone: "Africa" },
  { code: "TH", name: "Thailand", zone: "Asia" },
  { code: "TL", name: "Timor-Leste", zone: "Asia" },
  { code: "TG", name: "Togo", zone: "Africa" },
  { code: "TK", name: "Tokelau", zone: "Oceania" },
  { code: "TO", name: "Tonga", zone: "Oceania" },
  { code: "TT", name: "Trinidad and Tobago", zone: "North America" },
  { code: "TN", name: "Tunisia", zone: "Africa" },
  { code: "TR", name: "Türkiye", zone: "Asia" },
  { code: "TM", name: "Turkmenistan", zone: "Asia" },
  { code: "TC", name: "Turks and Caicos Islands", zone: "North America" },
  { code: "TV", name: "Tuvalu", zone: "Oceania" },
  { code: "UG", name: "Uganda", zone: "Africa" },
  { code: "UA", name: "Ukraine", zone: "Europe" },
  { code: "AE", name: "United Arab Emirates", zone: "Asia" },
  { code: "GB", name: "United Kingdom", zone: "Europe" },
  { code: "US", name: "United States", zone: "North America" },
  { code: "UM", name: "United States Minor Outlying Islands", zone: "Oceania" },
  { code: "UY", name: "Uruguay", zone: "South America" },
  { code: "UZ", name: "Uzbekistan", zone: "Asia" },
  { code: "VU", name: "Vanuatu", zone: "Oceania" },
  { code: "VE", name: "Venezuela", zone: "South America" },
  { code: "VN", name: "Viet Nam", zone: "Asia" },
  { code: "VG", name: "Virgin Islands (British)", zone: "North America" },
  { code: "VI", name: "Virgin Islands (U.S.)", zone: "North America" },
  { code: "WF", name: "Wallis and Futuna", zone: "Oceania" },
  { code: "EH", name: "Western Sahara", zone: "Africa" },
  { code: "YE", name: "Yemen", zone: "Asia" },
  { code: "ZM", name: "Zambia", zone: "Africa" },
  { code: "ZW", name: "Zimbabwe", zone: "Africa" },
];

const BY_CODE: Map<string, Country> = new Map(
  COUNTRIES.map((c) => [c.code, c]),
);

/** Look up a country by alpha-2 code (case-insensitive). */
export function countryByCode(code: string | null | undefined): Country | null {
  if (!code) return null;
  return BY_CODE.get(code.trim().toUpperCase()) ?? null;
}

/** True when `code` is a recognised country in the dataset. */
export function isValidCountryCode(code: string | null | undefined): boolean {
  return countryByCode(code) !== null;
}
