/**
 * Drizzle schema — the single import surface for the database shape.
 *
 * `tables.ts` and `relations.ts` are GENERATED by `drizzle-kit introspect` from
 * the live database; do not hand-edit them. Change the database via a migration
 * in `db/migrations/`, then re-introspect (`npm run db:introspect`).
 *
 * This is infrastructure. Nothing in `src/domain`, `src/application`,
 * `src/app` or `src/components` may import it — the ESLint layer rule in
 * eslint.config.mjs enforces that. Repository adapters are the only consumers.
 */
export * from "./tables";
export * from "./relations";
// Hand-written (not introspected): Better Auth's tables and admin invites.
export * from "./auth";
export * from "./admin";
