/**
 * GENERATED by `drizzle-kit introspect` from the live database. Do not hand-edit
 * to change the schema: write a migration in db/migrations/, apply it, then
 * re-run `npm run db:introspect`.
 *
 * THREE FIXES MUST BE RE-APPLIED after every re-introspection (drizzle-kit emits
 * invalid or incomplete TypeScript for each):
 *
 *   1. `knowledge_chunks.tsv` comes back as `unknown("tsv")` with a "failed to
 *      parse database type 'tsvector'" TODO. Replace with `tsvector("tsv")`
 *      from ./types.
 *   2. `shipping_settings_id_check` comes back as sql`CHECK (id)`, which
 *      renders as `CHECK (CHECK (id))`. Replace with sql`id`. (The column is a
 *      boolean defaulting to true — the standard single-row-table guard.)
 *   3. `profiles.id` loses its foreign key to the identity table, because
 *      introspection runs before Better Auth's tables exist. Re-add the
 *      `profiles_id_auth_user_id_fk` block on `profiles`.
 *   4. `products.lookbook` is declared by hand (see the column comment). It
 *      WILL come back from a re-introspection, so this note only matters if
 *      the file is regenerated against an older database.
 */
import { tsvector } from "./types";
import { user as authUser } from "./auth";
import { pgTable, text, timestamp, index, foreignKey, check, uuid, integer, boolean, jsonb, uniqueIndex, unique, date, smallint, doublePrecision, primaryKey, pgEnum } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

export const orderStatus = pgEnum("order_status", ['pending', 'paid', 'fulfilled', 'cancelled', 'processing', 'packed', 'shipped', 'out_for_delivery', 'delivered'])
export const productStatus = pgEnum("product_status", ['draft', 'published', 'archived'])
export const userRole = pgEnum("user_role", ['customer', 'admin'])


export const adminAllowlist = pgTable("admin_allowlist", {
	email: text().primaryKey().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const aiMessages = pgTable("ai_messages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	conversationId: uuid("conversation_id").notNull(),
	role: text().notNull(),
	content: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ai_messages_conversation_idx").using("btree", table.conversationId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.conversationId],
			foreignColumns: [aiConversations.id],
			name: "ai_messages_conversation_id_fkey"
		}).onDelete("cascade"),
	check("ai_messages_role_check", sql`role = ANY (ARRAY['user'::text, 'assistant'::text, 'agent'::text, 'system'::text])`),
]);

export const aiFaqs = pgTable("ai_faqs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	question: text().notNull(),
	answer: text().notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ai_faqs_order_idx").using("btree", table.enabled.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops")),
]);

export const automationLogs = pgTable("automation_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	automation: text().notNull(),
	subscriberId: uuid("subscriber_id"),
	campaignId: uuid("campaign_id"),
	provider: text(),
	status: text().default('queued').notNull(),
	error: text(),
	payload: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("automation_logs_automation_idx").using("btree", table.automation.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
	index("automation_logs_dedupe_idx").using("btree", table.subscriberId.asc().nullsLast().op("timestamptz_ops"), table.automation.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("automation_logs_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("automation_logs_subscriber_idx").using("btree", table.subscriberId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.campaignId],
			foreignColumns: [emailCampaigns.id],
			name: "automation_logs_campaign_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.subscriberId],
			foreignColumns: [newsletterSubscribers.id],
			name: "automation_logs_subscriber_id_fkey"
		}).onDelete("cascade"),
	check("automation_logs_automation_check", sql`automation = ANY (ARRAY['welcome'::text, 'birthday'::text, 'new_collection'::text, 'vip_invitation'::text, 'flash_sale'::text, 'back_in_stock'::text, 'style_guide'::text, 'seasonal'::text, 'abandoned_cart'::text, 'review_request'::text, 'order_followup'::text])`),
	check("automation_logs_status_check", sql`status = ANY (ARRAY['queued'::text, 'sent'::text, 'failed'::text, 'skipped'::text])`),
]);

export const discountCodes = pgTable("discount_codes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	code: text().notNull(),
	description: text(),
	campaign: text(),
	kind: text().notNull(),
	percentBps: integer("percent_bps"),
	amountKobo: integer("amount_kobo"),
	minSubtotalKobo: integer("min_subtotal_kobo").default(0).notNull(),
	maxDiscountKobo: integer("max_discount_kobo"),
	firstTimeOnly: boolean("first_time_only").default(false).notNull(),
	startsAt: timestamp("starts_at", { withTimezone: true, mode: 'string' }),
	endsAt: timestamp("ends_at", { withTimezone: true, mode: 'string' }),
	usageLimit: integer("usage_limit"),
	usedCount: integer("used_count").default(0).notNull(),
	perCustomerLimit: integer("per_customer_limit"),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("discount_codes_campaign_idx").using("btree", table.campaign.asc().nullsLast().op("text_ops")),
	uniqueIndex("discount_codes_code_key").using("btree", sql`upper(code)`),
	index("discount_codes_enabled_idx").using("btree", table.enabled.asc().nullsLast().op("timestamptz_ops"), table.startsAt.asc().nullsLast().op("bool_ops"), table.endsAt.asc().nullsLast().op("bool_ops")),
	check("discount_codes_amount_kobo_check", sql`amount_kobo >= 0`),
	check("discount_codes_kind_check", sql`kind = ANY (ARRAY['percent'::text, 'fixed'::text, 'free_shipping'::text])`),
	check("discount_codes_max_discount_kobo_check", sql`max_discount_kobo >= 0`),
	check("discount_codes_min_subtotal_kobo_check", sql`min_subtotal_kobo >= 0`),
	check("discount_codes_per_customer_limit_check", sql`(per_customer_limit IS NULL) OR (per_customer_limit > 0)`),
	check("discount_codes_percent_bps_check", sql`(percent_bps >= 0) AND (percent_bps <= 10000)`),
	check("discount_codes_usage_limit_check", sql`(usage_limit IS NULL) OR (usage_limit > 0)`),
	check("discount_codes_used_count_check", sql`used_count >= 0`),
	check("discount_codes_value_matches_kind", sql`((kind = 'percent'::text) AND (percent_bps IS NOT NULL)) OR ((kind = 'fixed'::text) AND (amount_kobo IS NOT NULL)) OR (kind = 'free_shipping'::text)`),
]);

export const aiSettings = pgTable("ai_settings", {
	id: text().default('default').primaryKey().notNull(),
	enabled: boolean().default(false).notNull(),
	welcomeMessage: text("welcome_message").default('Welcome to Fancy Finery. I\'m your personal concierge — ask me about our pieces, sizing, fabrics, shipping, or anything else.').notNull(),
	persona: text().default('You are the personal shopping concierge for Fancy Finery, a luxury fashion house. Speak with warm, refined elegance — poised and concise, never pushy. You are knowledgeable about style, fit, and fabric.').notNull(),
	model: text().default('claude-opus-5').notNull(),
	suggestedQuestions: jsonb("suggested_questions").default(["What''s new this season?","Help me choose the right size","What are your shipping options?","What''s your return policy?"]).notNull(),
	quickActions: jsonb("quick_actions").default([{"href":"/collections","label":"Shop Collections"},{"href":"/account","label":"Track Order"},{"href":"/shipping","label":"Shipping Info"},{"href":"/contact","label":"Contact Support"}]).notNull(),
	humanHandoff: boolean("human_handoff").default(false).notNull(),
	handoffMessage: text("handoff_message").default('I\'ll connect you with our team — please reach us at the contact page and we\'ll be delighted to help personally.').notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	check("ai_settings_id_check", sql`id = 'default'::text`),
]);

export const categories = pgTable("categories", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	description: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("categories_slug_key").on(table.slug),
]);

export const colorRequests = pgTable("color_requests", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	productId: uuid("product_id"),
	productName: text("product_name").notNull(),
	productSku: text("product_sku"),
	requestedColor: text("requested_color").notNull(),
	requestedSize: text("requested_size"),
	quantity: integer().default(1).notNull(),
	customerName: text("customer_name").notNull(),
	customerEmail: text("customer_email").notNull(),
	customerPhone: text("customer_phone"),
	note: text(),
	status: text().default('pending').notNull(),
	adminNote: text("admin_note"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("color_requests_color_idx").using("btree", table.requestedColor.asc().nullsLast().op("text_ops")),
	index("color_requests_created_idx").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("color_requests_product_idx").using("btree", table.productId.asc().nullsLast().op("uuid_ops")),
	index("color_requests_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "color_requests_product_id_fkey"
		}).onDelete("set null"),
	check("color_requests_quantity_check", sql`quantity > 0`),
	check("color_requests_status_check", sql`status = ANY (ARRAY['pending'::text, 'available'::text, 'in_production'::text, 'ready'::text, 'completed'::text, 'cancelled'::text])`),
]);

export const colors = pgTable("colors", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	colorName: text("color_name").notNull(),
	colorCode: text("color_code"),
	active: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("colors_active_idx").using("btree", table.active.asc().nullsLast().op("bool_ops")),
	unique("colors_color_name_key").on(table.colorName),
]);

export const discountRedemptions = pgTable("discount_redemptions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	codeId: uuid("code_id").notNull(),
	orderId: uuid("order_id"),
	userId: uuid("user_id"),
	amountKobo: integer("amount_kobo").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("discount_redemptions_code_idx").using("btree", table.codeId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	uniqueIndex("discount_redemptions_once_per_order").using("btree", table.codeId.asc().nullsLast().op("uuid_ops"), table.orderId.asc().nullsLast().op("uuid_ops")).where(sql`(order_id IS NOT NULL)`),
	index("discount_redemptions_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.codeId],
			foreignColumns: [discountCodes.id],
			name: "discount_redemptions_code_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "discount_redemptions_order_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [profiles.id],
			name: "discount_redemptions_user_id_fkey"
		}).onDelete("set null"),
]);

export const emailTemplates = pgTable("email_templates", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	key: text().notNull(),
	name: text().notNull(),
	subject: text().notNull(),
	html: text().notNull(),
	textBody: text("text_body"),
	description: text(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("email_templates_active_idx").using("btree", table.isActive.asc().nullsLast().op("bool_ops")),
	unique("email_templates_key_key").on(table.key),
]);

export const aiConversations = pgTable("ai_conversations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	token: uuid().defaultRandom().notNull(),
	userId: uuid("user_id"),
	contactEmail: text("contact_email"),
	status: text().default('bot').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	lastMessageAt: timestamp("last_message_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ai_conversations_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops"), table.lastMessageAt.desc().nullsFirst().op("text_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [profiles.id],
			name: "ai_conversations_user_id_fkey"
		}).onDelete("set null"),
	unique("ai_conversations_token_key").on(table.token),
	check("ai_conversations_status_check", sql`status = ANY (ARRAY['bot'::text, 'awaiting_human'::text, 'human'::text, 'closed'::text])`),
]);

export const campaignAnalytics = pgTable("campaign_analytics", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	campaignId: uuid("campaign_id").notNull(),
	subscriberId: uuid("subscriber_id"),
	event: text().notNull(),
	url: text(),
	userAgent: text("user_agent"),
	ipHash: text("ip_hash"),
	meta: jsonb().default({}).notNull(),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("campaign_analytics_campaign_event_idx").using("btree", table.campaignId.asc().nullsLast().op("text_ops"), table.event.asc().nullsLast().op("text_ops")),
	index("campaign_analytics_occurred_idx").using("btree", table.occurredAt.desc().nullsFirst().op("timestamptz_ops")),
	index("campaign_analytics_subscriber_idx").using("btree", table.subscriberId.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("campaign_analytics_unique_engagement").using("btree", table.campaignId.asc().nullsLast().op("text_ops"), table.subscriberId.asc().nullsLast().op("text_ops"), table.event.asc().nullsLast().op("text_ops")).where(sql`(event = ANY (ARRAY['opened'::text, 'clicked'::text, 'converted'::text, 'unsubscribed'::text]))`),
	foreignKey({
			columns: [table.campaignId],
			foreignColumns: [emailCampaigns.id],
			name: "campaign_analytics_campaign_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.subscriberId],
			foreignColumns: [newsletterSubscribers.id],
			name: "campaign_analytics_subscriber_id_fkey"
		}).onDelete("set null"),
	check("campaign_analytics_event_check", sql`event = ANY (ARRAY['queued'::text, 'sent'::text, 'delivered'::text, 'opened'::text, 'clicked'::text, 'bounced'::text, 'complained'::text, 'unsubscribed'::text, 'converted'::text])`),
]);

export const emailCampaigns = pgTable("email_campaigns", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	subject: text().notNull(),
	preheader: text(),
	html: text(),
	textBody: text("text_body"),
	templateId: uuid("template_id"),
	status: text().default('draft').notNull(),
	audienceFilter: jsonb("audience_filter").default({}).notNull(),
	scheduledAt: timestamp("scheduled_at", { withTimezone: true, mode: 'string' }),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'string' }),
	provider: text(),
	recipientCount: integer("recipient_count").default(0).notNull(),
	sentCount: integer("sent_count").default(0).notNull(),
	openCount: integer("open_count").default(0).notNull(),
	clickCount: integer("click_count").default(0).notNull(),
	conversionCount: integer("conversion_count").default(0).notNull(),
	bounceCount: integer("bounce_count").default(0).notNull(),
	unsubscribeCount: integer("unsubscribe_count").default(0).notNull(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("email_campaigns_created_idx").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("email_campaigns_scheduled_idx").using("btree", table.scheduledAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(status = 'scheduled'::text)`),
	index("email_campaigns_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [profiles.id],
			name: "email_campaigns_created_by_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.templateId],
			foreignColumns: [emailTemplates.id],
			name: "email_campaigns_template_id_fkey"
		}).onDelete("set null"),
	check("email_campaigns_status_check", sql`status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'sending'::text, 'sent'::text, 'cancelled'::text, 'failed'::text])`),
]);

export const ngDestinations = pgTable("ng_destinations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	stateId: uuid("state_id").notNull(),
	name: text().notNull(),
	priceKobo: integer("price_kobo").notNull(),
	enabled: boolean().default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ng_destinations_state_idx").using("btree", table.stateId.asc().nullsLast().op("int4_ops"), table.enabled.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops"), table.name.asc().nullsLast().op("int4_ops")),
	uniqueIndex("ng_destinations_state_name_key").using("btree", sql`state_id`, sql`lower(name)`),
	foreignKey({
			columns: [table.stateId],
			foreignColumns: [ngStates.id],
			name: "ng_destinations_state_id_fkey"
		}).onDelete("cascade"),
	check("ng_destinations_price_kobo_check", sql`price_kobo >= 0`),
]);

export const knowledgeDocuments = pgTable("knowledge_documents", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	title: text().notNull(),
	content: text().notNull(),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const newsletterSubscribers = pgTable("newsletter_subscribers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name"),
	country: text(),
	birthday: date(),
	status: text().default('subscribed').notNull(),
	source: text().default('homepage').notNull(),
	consent: boolean().default(true).notNull(),
	consentAt: timestamp("consent_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	consentText: text("consent_text"),
	ipHash: text("ip_hash"),
	userAgent: text("user_agent"),
	unsubscribeToken: uuid("unsubscribe_token").defaultRandom().notNull(),
	confirmedAt: timestamp("confirmed_at", { withTimezone: true, mode: 'string' }),
	unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true, mode: 'string' }),
	lastEmailedAt: timestamp("last_emailed_at", { withTimezone: true, mode: 'string' }),
	profileId: uuid("profile_id"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("newsletter_subscribers_birthday_idx").using("btree", sql`EXTRACT(month FROM birthday)`, sql`EXTRACT(day FROM birthday)`).where(sql`(birthday IS NOT NULL)`),
	index("newsletter_subscribers_country_idx").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("newsletter_subscribers_created_idx").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	uniqueIndex("newsletter_subscribers_email_key").using("btree", sql`lower(email)`),
	index("newsletter_subscribers_ip_recent_idx").using("btree", table.ipHash.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
	index("newsletter_subscribers_profile_idx").using("btree", table.profileId.asc().nullsLast().op("uuid_ops")),
	index("newsletter_subscribers_source_idx").using("btree", table.source.asc().nullsLast().op("text_ops")),
	index("newsletter_subscribers_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops")),
	uniqueIndex("newsletter_subscribers_token_key").using("btree", table.unsubscribeToken.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.profileId],
			foreignColumns: [profiles.id],
			name: "newsletter_subscribers_profile_id_fkey"
		}).onDelete("set null"),
	check("newsletter_subscribers_source_check", sql`source = ANY (ARRAY['homepage'::text, 'modal'::text, 'footer'::text, 'checkout'::text, 'admin'::text, 'import'::text])`),
	check("newsletter_subscribers_status_check", sql`status = ANY (ARRAY['pending'::text, 'subscribed'::text, 'unsubscribed'::text, 'bounced'::text, 'complained'::text])`),
]);

export const ngStates = pgTable("ng_states", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	code: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("ng_states_name_key").using("btree", sql`lower(name)`),
]);

export const orderItems = pgTable("order_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	orderId: uuid("order_id").notNull(),
	productId: uuid("product_id"),
	variantId: uuid("variant_id"),
	nameSnapshot: text("name_snapshot").notNull(),
	unitPrice: integer("unit_price").notNull(),
	qty: integer().notNull(),
}, (table) => [
	index("order_items_order_idx").using("btree", table.orderId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "order_items_order_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "order_items_product_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.variantId],
			foreignColumns: [productVariants.id],
			name: "order_items_variant_id_fkey"
		}).onDelete("set null"),
	check("order_items_qty_check", sql`qty > 0`),
	check("order_items_unit_price_check", sql`unit_price >= 0`),
]);

export const productReviews = pgTable("product_reviews", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	productId: uuid("product_id").notNull(),
	profileId: uuid("profile_id"),
	authorName: text("author_name").notNull(),
	rating: smallint().notNull(),
	title: text(),
	body: text().notNull(),
	orderId: uuid("order_id"),
	verified: boolean().default(false).notNull(),
	status: text().default('pending').notNull(),
	fitFeedback: text("fit_feedback"),
	helpfulCount: integer("helpful_count").default(0).notNull(),
	adminNote: text("admin_note"),
	ipHash: text("ip_hash"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("product_reviews_ip_recent_idx").using("btree", table.ipHash.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
	uniqueIndex("product_reviews_one_per_customer").using("btree", table.productId.asc().nullsLast().op("uuid_ops"), table.profileId.asc().nullsLast().op("uuid_ops")).where(sql`(profile_id IS NOT NULL)`),
	index("product_reviews_profile_idx").using("btree", table.profileId.asc().nullsLast().op("uuid_ops")),
	index("product_reviews_public_idx").using("btree", table.productId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")).where(sql`(status = 'approved'::text)`),
	index("product_reviews_status_idx").using("btree", table.status.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "product_reviews_order_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "product_reviews_product_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.profileId],
			foreignColumns: [profiles.id],
			name: "product_reviews_profile_id_fkey"
		}).onDelete("set null"),
	check("product_reviews_body_check", sql`(char_length(body) >= 10) AND (char_length(body) <= 4000)`),
	check("product_reviews_fit_feedback_check", sql`(fit_feedback IS NULL) OR (fit_feedback = ANY (ARRAY['small'::text, 'true'::text, 'large'::text]))`),
	check("product_reviews_rating_check", sql`(rating >= 1) AND (rating <= 5)`),
	check("product_reviews_status_check", sql`status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'spam'::text])`),
]);

export const productImages = pgTable("product_images", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	productId: uuid("product_id").notNull(),
	storagePath: text("storage_path").notNull(),
	alt: text(),
	sortOrder: integer("sort_order").default(0).notNull(),
	mediaType: text("media_type").default('image').notNull(),
}, (table) => [
	index("product_images_product_idx").using("btree", table.productId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "product_images_product_id_fkey"
		}).onDelete("cascade"),
	check("product_images_media_type_check", sql`media_type = ANY (ARRAY['image'::text, 'video'::text])`),
]);

export const products = pgTable("products", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	description: text(),
	price: integer().notNull(),
	currency: text().default('NGN').notNull(),
	categoryId: uuid("category_id"),
	status: productStatus().default('draft').notNull(),
	featured: boolean().default(false).notNull(),
	/**
	 * Whether this product appears in the Lookbook.
	 *
	 * The lookbook is an editorial surface, not a catalogue dump: it previously
	 * showed "the first eight published products that happen to have an image",
	 * which meant its contents changed whenever anything was added and no one
	 * could choose what appeared. This is the rule now, and it is the admin's to
	 * set — deliberately separate from `featured`, which drives the homepage row,
	 * so a piece can headline the shop without being campaign photography.
	 */
	lookbook: boolean().default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	weightGrams: integer("weight_grams").default(0).notNull(),
	weightUnit: text("weight_unit").default('g').notNull(),
	fitType: text("fit_type").default('regular').notNull(),
	modelHeightCm: integer("model_height_cm"),
	modelWeightKg: integer("model_weight_kg"),
	modelSize: text("model_size"),
	ratingSum: integer("rating_sum").default(0).notNull(),
	ratingCount: integer("rating_count").default(0).notNull(),
}, (table) => [
	index("products_category_idx").using("btree", table.categoryId.asc().nullsLast().op("uuid_ops")),
	index("products_featured_idx").using("btree", table.featured.asc().nullsLast().op("bool_ops")).where(sql`featured`),
	index("products_fit_type_idx").using("btree", table.fitType.asc().nullsLast().op("text_ops")),
	index("products_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")),
	foreignKey({
			columns: [table.categoryId],
			foreignColumns: [categories.id],
			name: "products_category_id_fkey"
		}).onDelete("set null"),
	unique("products_slug_key").on(table.slug),
	check("products_fit_type_check", sql`fit_type = ANY (ARRAY['slim'::text, 'regular'::text, 'relaxed'::text, 'oversized'::text])`),
	check("products_model_height_cm_check", sql`(model_height_cm IS NULL) OR ((model_height_cm >= 100) AND (model_height_cm <= 250))`),
	check("products_model_weight_kg_check", sql`(model_weight_kg IS NULL) OR ((model_weight_kg >= 25) AND (model_weight_kg <= 250))`),
	check("products_price_check", sql`price >= 0`),
	check("products_weight_grams_check", sql`weight_grams >= 0`),
	check("products_weight_unit_check", sql`weight_unit = ANY (ARRAY['g'::text, 'kg'::text])`),
]);

export const productVariants = pgTable("product_variants", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	productId: uuid("product_id").notNull(),
	size: text(),
	color: text(),
	sku: text(),
	stockQty: integer("stock_qty").default(0).notNull(),
}, (table) => [
	index("product_variants_product_idx").using("btree", table.productId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "product_variants_product_id_fkey"
		}).onDelete("cascade"),
	unique("product_variants_sku_key").on(table.sku),
	check("product_variants_stock_qty_check", sql`stock_qty >= 0`),
]);

export const paymentEvents = pgTable("payment_events", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	provider: text().notNull(),
	eventId: text("event_id"),
	eventType: text("event_type"),
	reference: text(),
	orderId: uuid("order_id"),
	raw: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	processedAt: timestamp("processed_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("payment_events_order_idx").using("btree", table.orderId.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("payment_events_provider_event_id_key").using("btree", table.provider.asc().nullsLast().op("text_ops"), table.eventId.asc().nullsLast().op("text_ops")).where(sql`(event_id IS NOT NULL)`),
	index("payment_events_reference_idx").using("btree", table.reference.asc().nullsLast().op("text_ops")),
	index("payment_events_unprocessed_idx").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")).where(sql`(processed_at IS NULL)`),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "payment_events_order_id_fkey"
		}).onDelete("set null"),
]);

export const shippingCountries = pgTable("shipping_countries", {
	code: text().primaryKey().notNull(),
	name: text().notNull(),
	zone: text().notNull(),
	enabled: boolean().default(true).notNull(),
	standardPrice: integer("standard_price").default(0).notNull(),
	standardMinDays: integer("standard_min_days").default(3).notNull(),
	standardMaxDays: integer("standard_max_days").default(10).notNull(),
	expressPrice: integer("express_price"),
	expressMinDays: integer("express_min_days").default(1).notNull(),
	expressMaxDays: integer("express_max_days").default(4).notNull(),
	freeOver: integer("free_over"),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("shipping_countries_enabled_idx").using("btree", table.enabled.asc().nullsLast().op("bool_ops")),
	index("shipping_countries_zone_idx").using("btree", table.zone.asc().nullsLast().op("text_ops")),
	check("shipping_countries_express_max_days_check", sql`express_max_days >= 0`),
	check("shipping_countries_express_min_days_check", sql`express_min_days >= 0`),
	check("shipping_countries_express_price_check", sql`(express_price IS NULL) OR (express_price >= 0)`),
	check("shipping_countries_free_over_check", sql`(free_over IS NULL) OR (free_over >= 0)`),
	check("shipping_countries_standard_max_days_check", sql`standard_max_days >= 0`),
	check("shipping_countries_standard_min_days_check", sql`standard_min_days >= 0`),
	check("shipping_countries_standard_price_check", sql`standard_price >= 0`),
]);

export const shippingMethods = pgTable("shipping_methods", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	code: text().notNull(),
	name: text().notNull(),
	description: text(),
	rateSource: text("rate_source").default('table').notNull(),
	carrierCode: text("carrier_code"),
	carrierConfig: jsonb("carrier_config").default({}).notNull(),
	enabled: boolean().default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	minDays: integer("min_days").default(3).notNull(),
	maxDays: integer("max_days").default(10).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	displayName: text("display_name"),
	trackingUrlTemplate: text("tracking_url_template"),
}, (table) => [
	index("shipping_methods_enabled_idx").using("btree", table.enabled.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops")),
	unique("shipping_methods_code_key").on(table.code),
	check("shipping_methods_carrier_needs_code", sql`(rate_source <> 'carrier'::text) OR (carrier_code IS NOT NULL)`),
	check("shipping_methods_max_days_check", sql`max_days >= 0`),
	check("shipping_methods_min_days_check", sql`min_days >= 0`),
	check("shipping_methods_rate_source_check", sql`rate_source = ANY (ARRAY['table'::text, 'carrier'::text])`),
]);

export const orders = pgTable("orders", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userId: uuid("user_id").notNull(),
	status: orderStatus().default('processing').notNull(),
	total: integer().notNull(),
	currency: text().default('NGN').notNull(),
	paystackReference: text("paystack_reference"),
	shippingName: text("shipping_name"),
	shippingEmail: text("shipping_email"),
	shippingPhone: text("shipping_phone"),
	shippingAddress: text("shipping_address"),
	shippingCity: text("shipping_city"),
	shippingState: text("shipping_state"),
	shippingCountry: text("shipping_country"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	shippingLat: doublePrecision("shipping_lat"),
	shippingLng: doublePrecision("shipping_lng"),
	subtotal: integer().default(0).notNull(),
	shippingCost: integer("shipping_cost").default(0).notNull(),
	shippingMethod: text("shipping_method"),
	shippingCountryCode: text("shipping_country_code"),
	shippingPostal: text("shipping_postal"),
	shippingApartment: text("shipping_apartment"),
	trackingNumber: text("tracking_number"),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	paymentStatus: text("payment_status").default('unpaid').notNull(),
	paymentProvider: text("payment_provider"),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'string' }),
	/** Set once when a cancelled order's stock goes back on the shelf. */
	stockRestoredAt: timestamp("stock_restored_at", { withTimezone: true, mode: 'string' }),
	tax: integer().default(0).notNull(),
	discount: integer().default(0).notNull(),
	totalWeightGrams: integer("total_weight_grams").default(0).notNull(),
	discountCode: text("discount_code"),
	taxLabel: text("tax_label"),
	courierName: text("courier_name"),
	estimatedMinDays: integer("estimated_min_days"),
	estimatedMaxDays: integer("estimated_max_days"),
	paymentReference: text("payment_reference"),
}, (table) => [
	uniqueIndex("orders_payment_reference_key").using("btree", table.paymentReference.asc().nullsLast().op("text_ops")),
	index("orders_payment_status_idx").using("btree", table.paymentStatus.asc().nullsLast().op("text_ops")),
	index("orders_status_idx").using("btree", table.status.asc().nullsLast().op("enum_ops")),
	uniqueIndex("orders_tracking_number_key").using("btree", table.trackingNumber.asc().nullsLast().op("text_ops")).where(sql`(tracking_number IS NOT NULL)`),
	index("orders_user_idx").using("btree", table.userId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [profiles.id],
			name: "orders_user_id_fkey"
		}).onDelete("restrict"),
	unique("orders_paystack_reference_key").on(table.paystackReference),
	check("orders_total_check", sql`total >= 0`),
	check("orders_tax_check", sql`tax >= 0`),
	check("orders_discount_check", sql`discount >= 0`),
	check("orders_payment_status_check", sql`payment_status = ANY (ARRAY['unpaid'::text, 'paid'::text, 'failed'::text, 'refunded'::text])`),
	check("orders_shipping_cost_check", sql`shipping_cost >= 0`),
	check("orders_subtotal_check", sql`subtotal >= 0`),
	check("orders_total_weight_grams_check", sql`total_weight_grams >= 0`),
]);

export const shippingRates = pgTable("shipping_rates", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	zoneId: uuid("zone_id"),
	countryCode: text("country_code"),
	methodId: uuid("method_id").notNull(),
	bracketId: uuid("bracket_id").notNull(),
	price: integer().default(0).notNull(),
	freeOver: integer("free_over"),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("shipping_rates_country_key").using("btree", table.countryCode.asc().nullsLast().op("text_ops"), table.methodId.asc().nullsLast().op("text_ops"), table.bracketId.asc().nullsLast().op("uuid_ops")).where(sql`(country_code IS NOT NULL)`),
	index("shipping_rates_lookup_country_idx").using("btree", table.countryCode.asc().nullsLast().op("text_ops"), table.methodId.asc().nullsLast().op("text_ops")).where(sql`enabled`),
	index("shipping_rates_lookup_zone_idx").using("btree", table.zoneId.asc().nullsLast().op("uuid_ops"), table.methodId.asc().nullsLast().op("uuid_ops")).where(sql`enabled`),
	uniqueIndex("shipping_rates_zone_key").using("btree", table.zoneId.asc().nullsLast().op("uuid_ops"), table.methodId.asc().nullsLast().op("uuid_ops"), table.bracketId.asc().nullsLast().op("uuid_ops")).where(sql`(zone_id IS NOT NULL)`),
	foreignKey({
			columns: [table.bracketId],
			foreignColumns: [shippingWeightBrackets.id],
			name: "shipping_rates_bracket_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.methodId],
			foreignColumns: [shippingMethods.id],
			name: "shipping_rates_method_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.zoneId],
			foreignColumns: [shippingZones.id],
			name: "shipping_rates_zone_id_fkey"
		}).onDelete("cascade"),
	check("shipping_rates_free_over_check", sql`(free_over IS NULL) OR (free_over >= 0)`),
	check("shipping_rates_one_scope", sql`((zone_id IS NOT NULL) AND (country_code IS NULL)) OR ((zone_id IS NULL) AND (country_code IS NOT NULL))`),
	check("shipping_rates_price_check", sql`price >= 0`),
]);

export const profiles = pgTable("profiles", {
	id: uuid().primaryKey().notNull(),
	fullName: text("full_name"),
	avatarUrl: text("avatar_url"),
	role: userRole().default('customer').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	phone: text(),
	address: text(),
	city: text(),
	state: text(),
	country: text(),
	lat: doublePrecision(),
	lng: doublePrecision(),
}, (table) => [
	// Post-introspect fix #3 (see file header): profiles is 1:1 with the
	// identity table. Under Supabase this FK pointed at auth.users; it now
	// points at Better Auth's auth_user. Deleting a user deletes their profile,
	// which is what the original ON DELETE CASCADE did.
	foreignKey({
			columns: [table.id],
			foreignColumns: [authUser.id],
			name: "profiles_id_auth_user_id_fk"
		}).onDelete("cascade"),
]);

export const shippingZoneCountries = pgTable("shipping_zone_countries", {
	countryCode: text("country_code").primaryKey().notNull(),
	zoneId: uuid("zone_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("shipping_zone_countries_zone_idx").using("btree", table.zoneId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.zoneId],
			foreignColumns: [shippingZones.id],
			name: "shipping_zone_countries_zone_id_fkey"
		}).onDelete("cascade"),
]);

export const subscriptionHistory = pgTable("subscription_history", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	subscriberId: uuid("subscriber_id"),
	email: text().notNull(),
	action: text().notNull(),
	source: text(),
	ipHash: text("ip_hash"),
	userAgent: text("user_agent"),
	meta: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("subscription_history_action_idx").using("btree", table.action.asc().nullsLast().op("text_ops")),
	index("subscription_history_email_idx").using("btree", sql`lower(email)`),
	index("subscription_history_ip_recent_idx").using("btree", table.ipHash.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("subscription_history_subscriber_idx").using("btree", table.subscriberId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.subscriberId],
			foreignColumns: [newsletterSubscribers.id],
			name: "subscription_history_subscriber_id_fkey"
		}).onDelete("cascade"),
	check("subscription_history_action_check", sql`action = ANY (ARRAY['subscribed'::text, 'resubscribed'::text, 'unsubscribed'::text, 'preferences_updated'::text, 'imported'::text, 'deleted'::text, 'bounced'::text])`),
]);

export const taxRules = pgTable("tax_rules", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	scope: text().notNull(),
	countryCode: text("country_code"),
	zoneId: uuid("zone_id"),
	rateBps: integer("rate_bps").default(0).notNull(),
	label: text().default('VAT').notNull(),
	appliesToShipping: boolean("applies_to_shipping").default(false).notNull(),
	enabled: boolean().default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("tax_rules_country_key").using("btree", table.countryCode.asc().nullsLast().op("text_ops")).where(sql`(scope = 'country'::text)`),
	index("tax_rules_enabled_idx").using("btree", table.enabled.asc().nullsLast().op("bool_ops")),
	uniqueIndex("tax_rules_global_key").using("btree", sql`(true)`).where(sql`(scope = 'global'::text)`),
	uniqueIndex("tax_rules_zone_key").using("btree", table.zoneId.asc().nullsLast().op("uuid_ops")).where(sql`(scope = 'zone'::text)`),
	foreignKey({
			columns: [table.zoneId],
			foreignColumns: [shippingZones.id],
			name: "tax_rules_zone_id_fkey"
		}).onDelete("cascade"),
	check("tax_rules_rate_bps_check", sql`(rate_bps >= 0) AND (rate_bps <= 10000)`),
	check("tax_rules_scope_check", sql`scope = ANY (ARRAY['global'::text, 'zone'::text, 'country'::text])`),
	check("tax_rules_scope_key", sql`((scope = 'global'::text) AND (country_code IS NULL) AND (zone_id IS NULL)) OR ((scope = 'zone'::text) AND (country_code IS NULL) AND (zone_id IS NOT NULL)) OR ((scope = 'country'::text) AND (country_code IS NOT NULL) AND (zone_id IS NULL))`),
]);

export const shippingWeightBrackets = pgTable("shipping_weight_brackets", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	label: text().notNull(),
	minGrams: integer("min_grams").notNull(),
	maxGrams: integer("max_grams"),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("shipping_weight_brackets_order_idx").using("btree", table.minGrams.asc().nullsLast().op("int4_ops")),
	unique("shipping_weight_brackets_min_key").on(table.minGrams),
	check("shipping_weight_brackets_check", sql`(max_grams IS NULL) OR (max_grams > min_grams)`),
	check("shipping_weight_brackets_min_grams_check", sql`min_grams >= 0`),
]);

export const shippingZones = pgTable("shipping_zones", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	code: text().notNull(),
	name: text().notNull(),
	enabled: boolean().default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("shipping_zones_enabled_idx").using("btree", table.enabled.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops")),
	unique("shipping_zones_code_key").on(table.code),
]);

export const shippingSettings = pgTable("shipping_settings", {
	id: boolean().default(true).primaryKey().notNull(),
	/**
	 * Exchange rates, expressed as NAIRA PER ONE UNIT of the foreign currency.
	 *
	 * NGN is the base: every catalogue price is stored in kobo, and a foreign
	 * price is derived as `kobo / (rate * 100)`. Storing it this way round means
	 * the number an admin types is the one they read in the news ("1600 naira to
	 * the dollar"), rather than its reciprocal.
	 *
	 * Integers, not decimals: naira-per-unit is in the thousands, so whole naira
	 * is finer precision than any FX desk quotes, and it keeps the money maths
	 * free of floating point.
	 */
	ngnPerUsd: integer("ngn_per_usd").default(1600).notNull(),
	ngnPerEur: integer("ngn_per_eur").default(1750).notNull(),
	ngnPerGbp: integer("ngn_per_gbp").default(2050).notNull(),
	/**
	 * Whether those rates actually price the storefront.
	 *
	 * OFF by default, and deliberately so. Until this is switched on the app uses
	 * its original "leading value" rule (₦300,000 reads as $300), which is NOT a
	 * conversion. Turning it on re-prices every non-NGN listing in one step — at
	 * 1600, that same garment becomes $187.50 — so it is an explicit decision an
	 * admin makes with the numbers in front of them, never a silent default.
	 */
	fxEnabled: boolean("fx_enabled").default(false).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	rateMode: text("rate_mode").default('auto').notNull(),
	rateSource: text("rate_source"),
	rateUpdatedAt: timestamp("rate_updated_at", { withTimezone: true, mode: 'string' }),
	taxRateBps: integer("tax_rate_bps").default(0).notNull(),
	taxLabel: text("tax_label").default('VAT').notNull(),
	taxEnabled: boolean("tax_enabled").default(false).notNull(),
	discountBps: integer("discount_bps").default(0).notNull(),
	discountLabel: text("discount_label").default('Discount').notNull(),
	discountEnabled: boolean("discount_enabled").default(false).notNull(),
	defaultItemWeightGrams: integer("default_item_weight_grams").default(500).notNull(),
}, (table) => [
	check("shipping_settings_id_check", sql`id`),
	check("shipping_settings_default_item_weight_grams_check", sql`default_item_weight_grams >= 0`),
	check("shipping_settings_discount_bps_check", sql`(discount_bps >= 0) AND (discount_bps <= 10000)`),
	check("shipping_settings_ngn_per_usd_check", sql`ngn_per_usd > 0`),
	check("shipping_settings_rate_mode_check", sql`rate_mode = ANY (ARRAY['auto'::text, 'manual'::text])`),
	check("shipping_settings_tax_rate_bps_check", sql`(tax_rate_bps >= 0) AND (tax_rate_bps <= 10000)`),
]);

export const knowledgeChunks = pgTable("knowledge_chunks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	documentId: uuid("document_id").notNull(),
	content: text().notNull(),
	tsv: tsvector("tsv").generatedAlwaysAs(sql`to_tsvector('english'::regconfig, content)`),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("knowledge_chunks_doc_idx").using("btree", table.documentId.asc().nullsLast().op("uuid_ops")),
	index("knowledge_chunks_tsv_idx").using("gin", table.tsv.asc().nullsLast().op("tsvector_ops")),
	foreignKey({
			columns: [table.documentId],
			foreignColumns: [knowledgeDocuments.id],
			name: "knowledge_chunks_document_id_fkey"
		}).onDelete("cascade"),
]);

export const newsletterPreferences = pgTable("newsletter_preferences", {
	subscriberId: uuid("subscriber_id").notNull(),
	interest: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("newsletter_preferences_interest_idx").using("btree", table.interest.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.subscriberId],
			foreignColumns: [newsletterSubscribers.id],
			name: "newsletter_preferences_subscriber_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.subscriberId, table.interest], name: "newsletter_preferences_pkey"}),
	check("newsletter_preferences_interest_check", sql`interest = ANY (ARRAY['mens'::text, 'womens'::text, 'childrens'::text, 'shoes'::text, 'accessories'::text, 'luxury'::text])`),
]);
